services:
  - type: web
    name: developer.caido.io
    runtime: static
    repo: https://github.com/caido/developer.caido.io.git
    branch: main
    buildCommand: make build-release
    staticPublishPath: ./.vitepress/dist
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /stats/script.js
        destination: https://plausible.io/js/plausible.js
      - type: rewrite
        source: /stats/event
        destination: https://plausible.io/api/event
    domains:
      - developer.caido.io
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true
